domain_path: /home/ran/seek_cytometer/software/seek_cytometer/export/seek_cytometer/sw/standalone_psu_cortexa53_0
app_src_dir: /opt/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
